spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory.root: ./data/index
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    spring:
#      jackson:
#        serialization:
#          FAIL_ON_EMPTY_BEANS=false:

application:
  signing:
    key:
      SECRET_KEY: DUMMY




